CREATE DATABASE SALUD
USE SALUD

CREATE TABLE PARS
(CEDULA VARCHAR(10),
NOMBRE_DEL_PARS VARCHAR(30),
EDAD VARCHAR(25),
DIRECCION VARCHAR(30),
TELEFONO VARCHAR(15))
SELECT*FROM PARS

DROP TABLE PARS

CREATE TABLE MEDICINAS
(CLAVE VARCHAR(10),
NÙMERO_DE_CONSULTA VARCHAR(5),
NOMBRE_DEL_PACIENTE VARCHAR(35),
EDAD VARCHAR(10),
FECHA_DE_NACIMIENTO VARCHAR(20),
SEXO VARCHAR(10),
NOMBRE_DEL_MEDICAMENTO VARCHAR(40),
CONTENIDO VARCHAR(10),
FECHA_DE_ENTREGA VARCHAR(10),
CANTIDAD VARCHAR(10),
USO_DE_MEDICAMENTO VARCHAR(60),
PRIMARY KEY(CLAVE))

SELECT*FROM MEDICINAS
DROP TABLE MEDICINAS